# Generated by Django 3.2.7 on 2021-09-11 01:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paginas', '0002_alter_campo_arquivo'),
    ]

    operations = [
        migrations.AddField(
            model_name='campo',
            name='nome',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='campo',
            name='arquivo',
            field=models.ImageField(upload_to=''),
        ),
    ]
