# Generated by Django 3.2.7 on 2021-09-11 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paginas', '0003_auto_20210910_2203'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campo',
            name='arquivo',
            field=models.ImageField(upload_to='uploads'),
        ),
    ]
