# Generated by Django 3.2.7 on 2021-09-11 21:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('paginas', '0004_alter_campo_arquivo'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Campo',
        ),
    ]
