# Generated by Django 3.2.7 on 2021-09-22 23:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('testes', '0003_upload_description'),
        ('filtros', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Teste',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filtro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='filtros.script')),
                ('imagem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testes.upload')),
            ],
        ),
    ]
