# Generated by Django 3.2.7 on 2021-09-23 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filtros', '0002_teste'),
    ]

    operations = [
        migrations.AlterField(
            model_name='script',
            name='codigo',
            field=models.TextField(help_text='Explicar como usar o código', max_length=255, verbose_name='Código'),
        ),
    ]
