# Generated by Django 3.2.7 on 2021-09-26 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filtros', '0003_alter_script_codigo'),
    ]

    operations = [
        migrations.AddField(
            model_name='script',
            name='categoria',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
