# Generated by Django 3.2.7 on 2021-10-17 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filtros', '0004_script_categoria'),
    ]

    operations = [
        migrations.AlterField(
            model_name='script',
            name='codigo',
            field=models.TextField(help_text='Substitua o endereço da imagem no script por: $Imagem$', max_length=255, verbose_name='Código'),
        ),
    ]
