# Generated by Django 3.0.3 on 2021-10-19 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filtros', '0006_auto_20211018_1458'),
    ]

    operations = [
        migrations.AlterField(
            model_name='script',
            name='categoria',
            field=models.CharField(help_text='escolha entre: imagem, limiarização, morfologia ou alguma outra personalizada', max_length=50),
        ),
        migrations.AlterField(
            model_name='script',
            name='codigo',
            field=models.TextField(help_text='image_in e image_out são arrays numpy.\n    atribua o valor da variavel image_out a partir de image_in.\n    caso não queira nenhuma modificação na imagem, faça: image_out=image_in', max_length=255, verbose_name='Código'),
        ),
        migrations.DeleteModel(
            name='Teste',
        ),
    ]
