# Generated by Django 3.2.7 on 2021-10-26 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filtros', '0008_auto_20211019_2214'),
    ]

    operations = [
        migrations.AlterField(
            model_name='script',
            name='categoria',
            field=models.CharField(help_text='Escolha entre: Imagem, Limiarização, Morfologia ou alguma outra personalizada', max_length=50),
        ),
        migrations.AlterField(
            model_name='script',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
