# Generated by Django 3.2.7 on 2021-09-22 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testes', '0002_auto_20210922_2011'),
    ]

    operations = [
        migrations.AddField(
            model_name='upload',
            name='description',
            field=models.CharField(default='imagem de teste', max_length=60, verbose_name='Descrição da imagem'),
            preserve_default=False,
        ),
    ]
