# Generated by Django 3.0.3 on 2021-10-18 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testes', '0004_auto_20211018_1458'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='action',
            field=models.CharField(choices=[('NO_FILTER', 'no filter'), ('COLORIZED', 'colorized'), ('GRAYSCALE', 'grayscale'), ('BLURRED', 'blurred'), ('BINARY', 'binary'), ('INVERT', 'invert')], default='default', help_text='Aqui você coloca um texto', max_length=50, verbose_name='Ação'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='image',
            name='description',
            field=models.CharField(default='default', max_length=60, verbose_name='Descrição da imagem'),
            preserve_default=False,
        ),
    ]
