# Generated by Django 3.2.7 on 2021-10-26 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testes', '0010_result_code_pk'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='result',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
